/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mandible.glb 
Author: University of Dundee, School of Dentistry (https://sketchfab.com/DundeeDental)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mandible-7a3c3b99916e481197e6f18fda107c15
Title: Mandible
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mandible(props) {
  const { nodes, materials } = useGLTF('/models/mandible.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Mandible_remesh_blinnSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blinn10SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.blinn10SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn25SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blinn25SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.blinn5SG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.blinn5SG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.blinn5SG} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.blinn8SG} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.blinn8SG} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.blinn9SG} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.blinn9SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mandible.glb')
